import { useState, type FormEvent } from 'react';
import { Plus, Trash2, Upload, Info } from 'lucide-react';
import { Modal } from '../common/Modal';
import { startCount, available, frozen, kindLabel, localDate, locations, number, productById, products, saveDocument, type Document, type Kind, type Line, type Session, type State } from '../../services/warehouse';
export function DocumentForm({ kind, state, session, close, save }: { kind: Kind; state: State; session: Session; close: () => void; save: (state: State) => void }) {
  const [partner, setPartner] = useState(kind === 'issue' ? 'Produksi' : kind === 'stock-count' ? '' : 'PT Sinar Tekstil');
  const [date, setDate] = useState(localDate()); const [reference, setReference] = useState(''); const [notes, setNotes] = useState('');
  const [lines, setLines] = useState<Line[]>([]); const [error, setError] = useState(''); const [attachment, setAttachment] = useState<Document['attachment']>(); const [uploading, setUploading] = useState(false);
  const [product, setProduct] = useState(products[0].id); const p = productById(product);
  const [location, setLocation] = useState('A-01'); const [batch, setBatch] = useState(''); const [expiry, setExpiry] = useState(''); const [quantity, setQuantity] = useState(''); const [documentQty, setDocumentQty] = useState('');
  const line: Line = { product, location, batch, expiry, quantity: Math.round(Number(quantity) * p.factor), documentQuantity: Math.round(Number(documentQty || quantity) * p.factor) };
  function add() { if (!quantity || Number(quantity) <= 0 || !Number.isSafeInteger(Number((Number(quantity) * p.factor).toFixed(8))) || (documentQty !== '' && (Number(documentQty) < 0 || !Number.isSafeInteger(Number((Number(documentQty) * p.factor).toFixed(8)))))) { setError('Isi kuantitas positif dan kuantitas surat jalan non-negatif dengan presisi sesuai satuan dasar.'); return; } if (p.batch && (!batch || !expiry)) { setError('Batch dan kedaluwarsa wajib diisi.'); return; } if (lines.some(l => l.product === product && l.location === location && l.batch === batch)) { setError('Material dengan lokasi dan batch ini sudah ditambahkan.'); return; } setLines([...lines, line]); setQuantity(''); setDocumentQty(''); setError(''); }
  function selectLocation(value: string) { setPartner(value); setLines(state.stocks.filter(s => s.warehouse === session.warehouse && s.location === value).map(s => ({ product: s.product, location: s.location, batch: s.batch, expiry: s.expiry, quantity: -1, documentQuantity: 0 }))); }
  function submit(event: FormEvent, draft: boolean) { event.preventDefault(); try { if (uploading) throw new Error('Tunggu foto selesai dibaca.'); save(saveDocument(state, session, { kind, date, status: draft ? 'DRAFT' : 'PENDING', partner, reference, notes, lines, attachment })); } catch (e) { setError((e as Error).message); } }
  if (['stock-count'].includes(kind)) return <Modal title="Mulai blind count" close={close}><p className="callout">Mulai sebelum menghitung fisik: snapshot disimpan dan lokasi dibekukan sampai posting atau pembatalan.</p><label>Lokasi<select value={partner} onChange={e => setPartner(e.target.value)}><option value="">Pilih lokasi</option>{locations.map(l => <option key={l} disabled={frozen(state, session.warehouse, l)}>{l}</option>)}</select></label>{error && <p className="error">{error}</p>}<button className="button primary" onClick={() => { try { save(startCount(state, session, partner)); } catch(e) { setError((e as Error).message); } }}>Mulai hitung</button></Modal>;
  return <Modal title={`Buat ${kindLabel[kind].toLowerCase()}`} close={close} wide><form onSubmit={e => submit(e, false)}>
    <div className="callout"><Info size={18}/><span>{kind === 'stock-count' ? 'Blind count: saldo sistem disembunyikan. Lokasi dibekukan setelah draft atau hasil disimpan.' : 'Stok berubah setelah verifikasi. Shift dicatat otomatis saat dokumen disimpan.'}</span></div>
    <div className="form-grid"><label>{kind === 'receiving' ? 'Supplier' : kind === 'issue' ? 'Alasan / tujuan' : 'Lokasi hitung'}{kind === 'receiving' ? <input required value={partner} onChange={e => setPartner(e.target.value)} placeholder="Nama supplier"/> : <select required value={partner} onChange={e => kind === 'stock-count' ? selectLocation(e.target.value) : setPartner(e.target.value)}>{kind === 'stock-count' && <option value="">Pilih lokasi</option>}{(kind === 'issue' ? ['Produksi', 'Rusak', 'Sampel', 'Lainnya'] : locations).map(v => <option key={v} disabled={kind === 'stock-count' && frozen(state, session.warehouse, v)}>{v}</option>)}</select>}</label><label>Tanggal dokumen<input required type="date" value={date} onChange={e => setDate(e.target.value)}/></label><label>Nomor referensi / surat jalan<input value={reference} onChange={e => setReference(e.target.value)} placeholder="Contoh: SJ-2026-001"/></label><label>Catatan / alasan khusus<input value={notes} onChange={e => setNotes(e.target.value)} placeholder="Tambahkan keterangan"/></label></div>
    {kind !== 'stock-count' && <div className="line-editor"><h3>Material</h3><div className="form-grid"><label>Produk<select value={product} onChange={e => { setProduct(e.target.value); setBatch(''); setExpiry(''); }}>{products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Lokasi rak<select value={location} onChange={e => setLocation(e.target.value)}>{locations.map(l => <option key={l} disabled={frozen(state, session.warehouse, l)}>{l}</option>)}</select></label>{p.batch && <><label>Batch{kind === 'issue' ? <select value={batch} onChange={e => { const s = state.stocks.find(s => s.warehouse === session.warehouse && s.product === product && s.location === location && s.batch === e.target.value); setBatch(e.target.value); setExpiry(s?.expiry ?? ''); }}><option value="">Pilih batch</option>{state.stocks.filter(s => s.warehouse === session.warehouse && s.product === product && s.location === location).sort((a,b) => a.expiry.localeCompare(b.expiry)).map(s => <option key={s.batch} value={s.batch}>{s.batch} - ED {s.expiry}</option>)}</select> : <input value={batch} onChange={e => setBatch(e.target.value)}/>}</label><label>Kedaluwarsa<input type="date" value={expiry} readOnly={kind === 'issue'} onChange={e => setExpiry(e.target.value)}/></label></>}<label>Kuantitas aktual ({p.inputUnit})<input type="number" min="0" step={1 / p.factor} value={quantity} onChange={e => setQuantity(e.target.value)}/></label>{kind === 'receiving' && <label>Kuantitas surat jalan ({p.inputUnit})<input type="number" min="0" step={1 / p.factor} value={documentQty} onChange={e => setDocumentQty(e.target.value)} placeholder="Sama dengan aktual"/></label>}</div>{kind === 'issue' && <p className="muted">Tersedia: {number(available(state, session.warehouse, line) / p.factor)} {p.inputUnit} {p.batch && ' - batch diurutkan berdasarkan kedaluwarsa.'}</p>}<button type="button" className="button secondary" onClick={add}><Plus size={16}/>Tambahkan material</button></div>}
    <div className="line-list">{lines.length === 0 && <p className="empty-inline">{kind === 'stock-count' ? 'Pilih lokasi untuk mulai menghitung.' : 'Belum ada material. Tambahkan item di atas.'}</p>}{lines.map((l, i) => { const product = productById(l.product); return <div className="line-item" key={`${l.product}-${l.location}-${l.batch}`}><div><strong>{product.name}</strong><small>{l.location}{l.batch ? ` / ${l.batch}` : ''}</small></div>{kind === 'stock-count' ? <label className="count-input">Hasil fisik ({product.inputUnit})<input aria-label={`Hasil fisik ${product.name}`} required type="number" min="0" step={1 / product.factor} value={l.quantity < 0 ? '' : l.quantity / product.factor} onChange={e => setLines(lines.map((x,j) => j === i ? { ...x, quantity: e.target.value === '' ? -1 : Number((Number(e.target.value) * product.factor).toFixed(8)) } : x))}/></label> : <><span>{number(l.quantity / product.factor)} {product.inputUnit}</span><button type="button" className="icon-button" aria-label={`Hapus ${product.name}`} onClick={() => setLines(lines.filter((_,j) => j !== i))}><Trash2 size={16}/></button></>}</div>; })}</div>
    <label className="upload"><Upload size={22}/><span>{uploading ? 'Membaca foto...' : attachment?.name || 'Tambahkan foto bukti'}<small>JPG / PNG, maksimum 1 MB. Disimpan lokal untuk demo.</small></span><input type="file" accept="image/jpeg,image/png" onChange={async e => { const file = e.target.files?.[0]; if (!file) return; if (!['image/jpeg', 'image/png'].includes(file.type) || file.size > 1024 * 1024) { setError('Gunakan gambar JPG/PNG maksimum 1 MB.'); e.target.value = ''; return; } setUploading(true); const reader = new FileReader(); reader.onload = () => { setAttachment({ name: file.name, data: String(reader.result) }); setUploading(false); }; reader.onerror = () => { setError('Foto gagal dibaca.'); setUploading(false); }; reader.readAsDataURL(file); }}/></label>
    {error && <p className="error" role="alert">{error}</p>}<div className="modal-footer"><button type="button" className="button secondary" disabled={uploading} onClick={e => submit(e, true)}>Simpan draft</button><button className="button primary" disabled={uploading} type="submit">Kirim untuk verifikasi</button></div>
  </form></Modal>;
}
