import { useEffect, useState } from 'react';
import { api, ApiError, type AuthSession, type CountDetail, type CountSummary } from '../services/api';
const reasons=['miscount','damaged','wrong_location','unrecorded_transaction','missing','other'];
interface Draft { product: string; batch: string; quantity: string; reason: string; explanation: string }
export function ConnectedWorkspace() {
 const [session,setSession]=useState<AuthSession|null>(null); const [warehouse,setWarehouse]=useState(''); const [boot,setBoot]=useState(true);
 const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [username,setUsername]=useState(''); const [password,setPassword]=useState('');
 const [counts,setCounts]=useState<CountSummary[]>([]); const [locations,setLocations]=useState<{id:string}[]>([]); const [location,setLocation]=useState(''); const [correction,setCorrection]=useState('');
 const [detail,setDetail]=useState<CountDetail|null>(null); const [draft,setDraft]=useState<Draft[]>([]); const [note,setNote]=useState(''); const [inventory,setInventory]=useState<{location:string;product:string;batch:string;quantity:number}[]>([]);
 const [page,setPage]=useState<'counts'|'inventory'>('counts'); const [message,setMessage]=useState('');
 const role=session?.memberships.find(m=>m.warehouse===warehouse)?.role;
 function fail(e: unknown) { setError(e instanceof Error?e.message:'Tidak dapat menghubungi server'); if(e instanceof ApiError && e.status===401) { setSession(null); setDetail(null); setCounts([]); setInventory([]); } }
 async function authenticate() { const s=await api<AuthSession>('/session'); setSession(s); setWarehouse(s.memberships[0]?.warehouse || ''); }
 useEffect(()=>{ void authenticate().catch(e=>{if(!(e instanceof ApiError && e.status===401)) fail(e);}).finally(()=>setBoot(false)); },[]);
 useEffect(()=>{
  let active=true; setDetail(null); setDraft([]); setCounts([]); setInventory([]); setLocations([]); setError(''); setCorrection(''); setPage('counts');
  if(!session || !warehouse) return;
  setBusy(true);
  void Promise.all([api<CountSummary[]>('/counts',warehouse),api<{locations:{id:string}[]}>('/master',warehouse)]).then(([c,m])=>{if(active){setCounts(c);setLocations(m.locations);setLocation(m.locations[0]?.id || '');}}).catch(e=>{if(active)fail(e);}).finally(()=>{if(active)setBusy(false);});
  return ()=>{active=false;};
 },[session,warehouse]);
 async function run(work: ()=>Promise<void>) { setBusy(true); setError(''); setMessage(''); try { await work(); } catch(e) { fail(e); } finally { setBusy(false); } }
 async function refresh() { setCounts(await api<CountSummary[]>('/counts',warehouse)); }
 async function open(id: string) { const d=await api<CountDetail>(`/counts/${id}`,warehouse); setDetail(d);setNote(''); setDraft(d.lines.map(l=>({product:l.product,batch:l.batch,quantity:l.counted_quantity===null?'':String(l.counted_quantity),reason:l.reason || '',explanation:l.explanation || ''}))); }
 async function command(action: string,input: unknown) {
  if(!detail) return;
  await api(action==='post'?`/adjustments/${detail.adjustment!.id}/post`:`/counts/${detail.id}/${action}`,warehouse,input,crypto.randomUUID());
  await refresh(); await open(detail.id); setMessage('Tersimpan di database server.');
 }
 function payload() { return {lines:draft.map(l=>{if(l.quantity.trim()==='' || !Number.isInteger(Number(l.quantity)) || Number(l.quantity)<0) throw new Error('Isi semua kuantitas dengan bilangan bulat non-negatif.'); return {product:l.product,batch:l.batch,quantity:Number(l.quantity),...(l.reason?{reason:l.reason}:{}),...(l.explanation?{explanation:l.explanation}:{})};})}; }
 function change(index:number,field:keyof Draft,value:string) { setDraft(draft.map((l,i)=>i===index?{...l,[field]:value}:l)); }
 if(boot) return <main className="connected-loading" role="status">Menghubungkan ke server...</main>;
 if(!session) return <div className="login-page"><section className="login-story"><div className="brand"><span className="brand-mark">b.</span><span>buymore<small>WAREHOUSE WORKSPACE</small></span></div><div><span className="eyebrow">KONTROL STOK TERHUBUNG</span><h1>Hitung dengan teliti.<br/><em>Putuskan dengan yakin.</em></h1><p>Blind count, verifikasi, dan adjustment dalam satu catatan server.</p></div></section><section className="login-form"><div className="login-inner"><span className="subtle-chip">SERVER WORKSPACE</span><h2>Masuk ke gudang.</h2><p>Akses dan peran ditentukan oleh akun Anda.</p><form onSubmit={e=>{e.preventDefault();void run(async()=>{await api('/login',undefined,{username,password});setPassword('');await authenticate();});}}><label>Username<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required maxLength={100}/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required maxLength={256}/></label>{error && <p className="connected-error" role="alert">{error}</p>}<button className="button primary" disabled={busy}>{busy?'Menghubungkan...':'Masuk'}</button></form><p>Sesi cookie HttpOnly. Tidak ada pemilihan peran di browser.</p></div></section></div>;
 return <div className="connected-shell"><aside className="connected-sidebar"><div className="brand"><span className="brand-mark">b.</span><span>buymore<small>WAREHOUSE WORKSPACE</small></span></div><p>{session.user.username} / {role || 'Tanpa akses'}</p><label>Gudang<select value={warehouse} disabled={busy} onChange={e=>setWarehouse(e.target.value)}>{session.memberships.map(m=><option key={m.warehouse}>{m.warehouse}</option>)}</select></label><button className="button" disabled={busy} onClick={()=>{setPage('counts');setDetail(null);}}>Stock count</button>{role && role!=='Staff' && <button className="button" disabled={busy} onClick={()=>void run(async()=>{setInventory(await api('/inventory',warehouse));setDetail(null);setPage('inventory');})}>Inventori</button>}<div className="connected-scope"><strong>Belum terintegrasi</strong><p>Receiving, issue, laporan, ekspor BigSeller, dan pengaturan dinonaktifkan. Tidak ada transaksi demo yang dianggap tersimpan ke server.</p></div><button className="button" disabled={busy} onClick={()=>void run(async()=>{await api('/logout',undefined,{});setSession(null);setDetail(null);setCounts([]);setInventory([]);})}>Keluar</button></aside><main className="connected-main"><header><span className="eyebrow">{warehouse} / {role}</span><h1>{page==='counts'?'Stock count':'Inventori'}</h1><p>Data server · kuantitas satuan dasar · {role==='Staff'?'blind count tanpa saldo sistem':'persetujuan dan posting terpisah'}</p></header>{error && <p className="connected-error" role="alert">{error}</p>}{message && <p role="status">{message}</p>}{busy && <p role="status">Memproses...</p>}{!warehouse && <p>Akun belum memiliki keanggotaan gudang. Hubungi operator.</p>}
 {page==='inventory' && <section className="connected-card"><div className="connected-table"><table><thead><tr><th>Lokasi</th><th>Produk</th><th>Batch</th><th>Saldo</th></tr></thead><tbody>{inventory.map((l,i)=><tr key={i}><td>{l.location}</td><td>{l.product}</td><td>{l.batch || '-'}</td><td>{l.quantity}</td></tr>)}</tbody></table></div>{!inventory.length && <p>Belum ada saldo tercatat.</p>}</section>}
 {page==='counts' && <>{role==='Staff' && !detail && <section className="connected-card"><h2>Mulai blind count</h2><p>Memulai hitung membekukan lokasi sampai count selesai atau dibatalkan.</p><form className="connected-inline" onSubmit={e=>{e.preventDefault();void run(async()=>{const c=await api<{id:string}>('/counts',warehouse,{location,...(correction?{correctionOf:correction}:{})},crypto.randomUUID());await refresh();await open(c.id);});}}><label>Lokasi<select value={location} onChange={e=>setLocation(e.target.value)}>{locations.map(l=><option key={l.id}>{l.id}</option>)}</select></label><label>Koreksi count selesai (opsional)<input value={correction} onChange={e=>setCorrection(e.target.value)} placeholder="ID count sebelumnya"/></label><button className="button primary" disabled={busy || !location}>Mulai hitung</button></form></section>}
 {!detail && <section className="connected-card"><div className="connected-inline"><h2>Dokumen terbaru</h2><button className="button" disabled={busy || !warehouse} onClick={()=>void run(refresh)}>Muat ulang</button></div><p>Maksimal 200 dokumen terbaru. Staff hanya melihat count miliknya.</p><div className="connected-table"><table><thead><tr><th>Dokumen</th><th>Lokasi</th><th>Status</th><th/></tr></thead><tbody>{counts.map(c=><tr key={c.id}><td><code>{c.id}</code></td><td>{c.location}</td><td>{c.status}</td><td><button className="button" disabled={busy} onClick={()=>void run(()=>open(c.id))}>Buka</button></td></tr>)}</tbody></table></div>{!counts.length && <p>Belum ada count.</p>}</section>}
 {detail && <section className="connected-card"><button className="button" disabled={busy} onClick={()=>setDetail(null)}>Kembali</button><h2>{detail.location} · {detail.status}</h2><p><code>{detail.id}</code></p>{detail.correction_of && <p>Koreksi dari {detail.correction_of}</p>}<div className="connected-table"><table><thead><tr><th>Produk</th><th>Batch</th>{role!=='Staff' && <th>Sistem</th>}<th>Hasil hitung</th>{role!=='Staff' && <><th>Alasan</th><th>Penjelasan</th></>}</tr></thead><tbody>{draft.map((l,i)=><tr key={i}><td>{role==='Staff' && detail.status==='COUNTING' && i>=detail.lines.length?<input aria-label="Produk baru" value={l.product} onChange={e=>change(i,'product',e.target.value)}/>:l.product}</td><td>{role==='Staff' && detail.status==='COUNTING' && i>=detail.lines.length?<input aria-label="Batch baru" value={l.batch} onChange={e=>change(i,'batch',e.target.value)}/>:l.batch || '-'}</td>{role!=='Staff' && <td>{detail.lines[i]?.system_quantity}</td>}<td><input aria-label={`Kuantitas ${l.product}`} type="number" min="0" max="2147483647" step="1" value={l.quantity} disabled={busy || role!=='Staff' || detail.status!=='COUNTING'} onChange={e=>change(i,'quantity',e.target.value)}/></td>{role!=='Staff' && <><td><select aria-label={`Alasan ${l.product}`} value={l.reason} disabled={busy || role!=='Admin' || detail.status!=='COUNTED'} onChange={e=>change(i,'reason',e.target.value)}><option value="">Pilih alasan</option>{reasons.map(r=><option key={r}>{r}</option>)}</select></td><td><input aria-label={`Penjelasan ${l.product}`} value={l.explanation} disabled={busy || role!=='Admin' || detail.status!=='COUNTED'} onChange={e=>change(i,'explanation',e.target.value)}/></td></>}</tr>)}</tbody></table></div>
 <div className="connected-actions">{role==='Staff' && detail.status==='COUNTING' && <><button className="button" disabled={busy} onClick={()=>setDraft([...draft,{product:'',batch:'',quantity:'',reason:'',explanation:''}])}>Tambah temuan</button><button className="button primary" disabled={busy} onClick={()=>void run(()=>command('submit',payload()))}>Kirim hasil hitung</button></>}{role==='Admin' && detail.status==='COUNTED' && <button className="button primary" disabled={busy} onClick={()=>void run(()=>command('verify',payload()))}>Verifikasi</button>}{role==='Head' && detail.status==='VERIFIED' && <button className="button primary" disabled={busy} onClick={()=>void run(()=>command('approve',{}))}>Setujui count (belum posting)</button>}{role==='Head' && detail.adjustment?.status==='PENDING' && <button className="button primary" disabled={busy} onClick={()=>void run(()=>command('post',{}))}>Setujui & posting adjustment</button>}</div>
 {!['COMPLETED','CANCELLED'].includes(detail.status) && <div className="connected-actions"><label>Alasan recount / pembatalan<input value={note} onChange={e=>setNote(e.target.value)} maxLength={2000}/></label>{role==='Admin' && detail.status==='COUNTED' && <button className="button" disabled={busy || !note.trim()} onClick={()=>void run(()=>command('recount',{reason:note}))}>Minta recount</button>}{(role==='Head' || (role==='Admin' && detail.status!=='APPROVED') || (role==='Staff' && detail.status==='COUNTING')) && <button className="button" disabled={busy || !note.trim()} onClick={()=>void run(()=>command('cancel',{reason:note}))}>Batalkan count</button>}</div>}{detail.adjustment && <p>Adjustment: {detail.adjustment.id} / {detail.adjustment.status}</p>}</section>}</>}
 </main></div>;
}
