import { useState } from 'react';
import { Download, History } from 'lucide-react';
import { kindLabel, number, productById, type Session, type State } from '../services/warehouse';
import { downloadCsv } from '../utils/download';
export function Reports({ state, session, search }: { state: State; session: Session; search: string }) {
  const [tab, setTab] = useState('transactions'); const [from, setFrom] = useState(''); const [to, setTo] = useState('');
  const inRange = (date: string) => (!from || date.slice(0,10) >= from) && (!to || date.slice(0,10) <= to);
  const docs = state.documents.filter(d => d.warehouse === session.warehouse && inRange(d.date) && `${d.id} ${d.partner}`.toLowerCase().includes(search.toLowerCase()));
  const ledger = state.ledger.filter(l => l.warehouse === session.warehouse && inRange(l.time) && `${l.document} ${productById(l.line.product).name}`.toLowerCase().includes(search.toLowerCase()));
  const audit = state.audit.filter(a => a.warehouse === session.warehouse && inRange(a.time) && `${a.document} ${a.actor} ${a.action}`.toLowerCase().includes(search.toLowerCase()));
  const auditAllowed = session.role === 'Head';
  const headers = tab === 'ledger' ? ['Dokumen','Material','Lokasi','Mutasi dasar','Satuan'] : tab === 'audit' && auditAllowed ? ['Waktu','Petugas','Aksi','Dokumen','Detail'] : ['Dokumen','Tanggal','Jenis','Supplier / tujuan','Status'];
  const rows: (string | number)[][] = tab === 'ledger' ? ledger.map(l => [l.document,productById(l.line.product).name,l.line.location,l.delta,productById(l.line.product).unit]) : tab === 'audit' && auditAllowed ? audit.map(a => [a.time,a.actor,a.action,a.document,a.detail]) : docs.map(d => [d.id,d.date,kindLabel[d.kind],d.partner,d.status]);
  return <><div className="page-heading"><div className="eyebrow">VISIBILITAS OPERASIONAL</div><div className="heading-row"><div><h1>Laporan & audit<span className="green-dot">.</span></h1><p>Setiap perubahan punya cerita. Telusuri dari sumbernya.</p></div><button className="button secondary" onClick={() => downloadCsv(`laporan-${tab}-demo.csv`,headers,rows)}><Download size={16}/>Unduh CSV</button></div></div><section className="panel"><div className="tabs">{[['transactions','Transaksi'],['ledger','Mutasi stok'],...(auditAllowed ? [['audit','Audit log']] : [])].map(([id,label]) => <button className={tab === id ? 'selected' : ''} key={id} onClick={() => setTab(id)}>{label}</button>)}</div><div className="filter-bar"><label>Dari tanggal<input type="date" value={from} onChange={e => setFrom(e.target.value)}/></label><label>Sampai tanggal<input type="date" value={to} onChange={e => setTo(e.target.value)}/></label><span className="muted">{number(rows.length)} catatan</span></div><div className="table-scroll"><table><thead><tr>{headers.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i) => <tr key={i}>{row.map((cell,j) => <td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>{!rows.length && <div className="empty"><History size={30}/><h3>Belum ada catatan</h3><p>Mutasi baru dicatat setelah verifikasi atau persetujuan adjustment. Saldo awal demo tidak ditampilkan sebagai transaksi baru.</p></div>}</section></>;
}
